---
title: "ggplot Visualizations"
author: "Grace Wang, Virginia Baskin, Siddhi Narayan"
date: "2023-02-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load in Stuff, include=FALSE}

library(ggplot2)
library(readr)
mini_htx <- read_csv("Datasets/mini_htx.csv")

```

## Plot 1: Yearly Citations by Race
```{r, include=FALSE}
# yearly citations stacked by race
race_date <- mini_htx[,c("date", "subject_race")] # race and date
race_date <- na.omit(race_date) # omit na Values

year_only <- function(fulldate){
  year <- substring(fulldate, 1, 4) # only keep year
}
race_date$date <- unlist(lapply(race_date$date, year_only))
make_factor <- (race_date$date)

race_date <- as.data.frame(table(race_date))

# Stacked
ggplot(race_date, aes(fill=subject_race, y=Freq, x=date))+geom_bar(position="stack", stat="identity")+ggtitle("Police Citations in Houston 2014-2020 by Race")+xlab("Year")+ylab("Citations")+guides(fill=guide_legend(title='Subject Race'))

```

## Plot 2: MPH over Speed Limit for Speeding Citations 2014-2020
with marginal histogram 
virginia 

```{r}
mini_htx2 <- mini_htx
mini_htx2$diff <- (mini_htx2$speed - mini_htx2$posted_speed)
diff <- mini_htx2$diff


test <- ggplot(mini_htx2, aes(date, diff)) 
test + geom_point(width = .5, size=1) +
  labs(subtitle="mpg: city vs highway mileage", 
       y="hwy", 
       x="cty", 
       title="Jittered Points")

  
g <- ggplot(mini_htx2, aes(x=date, y=diff)) + geom_point()
g + geom_point() + 
  labs(subtitle="mpg: city vs highway mileage", 
       y="diff", 
       x="date", 
       title="Scatterplot with overlapping points", 
       caption="Source: midwest")

ggMarginal(g, type = "histogram", fill="transparent")
ggMarginal(g, type = "boxplot", fill="transparent")

##OLD
plot(mini_htx2$date, mini_htx2$diff, main = "MPH over Limit for Speeding Citations 2014-2020", 
     xlab = "Year", ylab = "MPH Speeding", pch = ".", panel.first = grid(10,10),ylim = c(0,100), 
     col = ifelse((diff <= 5), "dark green", 
                    ifelse((diff <= 10), "blue", 
                           ifelse((diff <= 15), "purple",
                                  ifelse((diff <= 20), "red", "dark orange")))))

legend("topleft", legend = c("0-5 mph", "6-10 mph", "11-15 mph", "16-20 mph", ">20 mph"), 
       col = c("dark green", "blue", "purple", "red", "dark orange"), pch = ".", cex = 0.7)
##
```


## Plot 3: Monthly Citations by District


## Plot 4: MPH over Speed Limit by Race and Gender
```{r, include=FALSE}
mini_htx4 <- na.omit(mini_htx2[,c("subject_race", "date", "diff", "subject_sex")])

ggplot(mini_htx4, aes(fill=factor(subject_sex),subject_race, diff)) + geom_violin() + labs(title="MPH over Speed Limit for Citation", x="Subject Race",y="MPH Speeding")+guides(fill=guide_legend(title='Subject Sex'))

```

## Plot 5: Citations by District and Gender
virginia


## Plot 6: Citations by Race