---
title: "Visualizations"
author: "Virginia Baskin, Siddhi Narayan, Grace Wang"
date: "2/19/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in dataset
```{r}
library(readr)
tx_houston <- read_csv("/Users/virginiabaskin/Downloads/tx_houston_2023_01_26.csv")
head(tx_houston)
```

### Created smaller dataset to work with initially.

Our computers were struggling to work with the entire dataset, so we created a mini dataset by randomly sampling 1,000 rows. We will use this dataset for creating the graphs/brainstorming, then we will run the code on the large dataset as a final step. 
```{r}
mini_htx <- read_csv("Datasets/mini_htx.csv")
mini_htx
```

```{r}
mini_htx
colSums(is.na(mini_htx))
```

```{r}
min(mini_htx$date)
max(mini_htx$date)
```

## Visualizations 

```{r Race Line Graph by Year}
# visualize totals for each race
# Grace


```

```{r Race to Citation Ratio (Paired Bar Graph)}
# x axis: race
# y axis: Count
# two bars per race for citation issued true and citation issued false
# visualize to investigate for evidence of racial bias
# Siddhi

```


```{r Line graph of number of citations}
# Observe arrests over time and any time-associate patterns
# Siddhi

```


```{r Scatter plot longitude vs latitude, color by district}
# verifying the hubs for arrest and locations of districts
# Virginia

```

```{r scatter plot of difference between speed and posted speed over time }
# if we want to do a line plot
# Virginia

```

```{r Citations by time of day histogram}
# x axis is the time of day
# y is frequency
# Grace

```